name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - "**"
jobs:
  check-test-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install PyGithub
        run: pip install PyGithub

      - name: Infer PR number and Check for /test command in comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
        run: python check_test_command.py "${{ secrets.GITHUB_TOKEN }}" "${{ github.repository }}" "$COMMIT_SHA"
