name: pull request comment
on:
  issue_comment:
    types: [created, edited, deleted]
  push:
    branches:
      - "**"
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: say hello
        # if: contains(github.event.comment.body, '/test') # check the comment if it contains the keywords
        run: |
          python3 test.py "${{ github.event.comment.body }}"
