name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      backend:
        description: "Backend for testing"
        required: true
        default: "development"
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set target branch
        id: set_branch
        run: |
          echo "TARGET_BRANCH=${{ github.event.inputs.backend || github.ref_name }}" >> $GITHUB_ENV

      - name: Use target branch
        run: |
          ping -c 1 $TARGET_BRANCH
